stages:
    - build
    - publish

build:win32:
    stage: build
    tags:
        - docker
    image: 7hazard/node-clang-win32-cross

    script:
        - "chmod -R 777 ./"
        - "./gradlew build buildModuleWin32Cross"

    artifacts:
        paths:
            - build/win32/altv-jvm-module/*
    
    variables:
        GIT_SUBMODULE_STRATEGY: recursive

    except:
        refs:
            - tags

build:linux:
    stage: build
    tags:
        - docker
    image: 7hazard/node-clang-7

    script:
        - "chmod -R 777 ./"
        - "./gradlew build buildModule"

    artifacts:
        paths:
            - build/linux/altv-jvm-module/*
    
    variables:
        GIT_SUBMODULE_STRATEGY: recursive

    except:
        refs:
            - tags

publish:
    stage: publish
    tags:
        - docker
    image: 7hazard/node-clang-7

    dependencies:
        - build:win32
        - build:linux
    
    script:
        - "echo Build ${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_IID} '|' Project ID ${CI_PROJECT_ID} '|' Job ID ${CI_JOB_ID} '|' API Key ${CI_GITLAB_API_PRIVATE_KEY}" 
        
        ## WIN32
        # client packaging
        - "cd build/win32 && zip -r ../altv-jvm-module-win32.zip altv-jvm-module && cd ../../"

        ## LINUX
        # server packaging
        - "cd build/linux && zip -r ../altv-jvm-module-linux.zip altv-jvm-module && cd ../../"
        
        ## PUBLISH
        # - "echo TESTING ENV VARS: $CI_TEST_VAL '|' $CI_TEST_VAL_MASKED '|' ${CI_TEST_VAL} '|' ${CI_TEST_VAL_MASKED}"
        # - "echo PUBLISHING"
        - "echo Build ${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_IID} '|' Project ID ${CI_PROJECT_ID} '|' Job ID ${CI_JOB_ID} '|' API Key ${CI_GITLAB_API_PRIVATE_KEY}" 
        
        # linux client builds, if there ever is a chance for that to be needed
        # { \\\"name\\\": \\\"client-linux\\\", \\\"url\\\": \\\"https://gitlab.com/7Hazard/altv-capi/-/jobs/${CI_JOB_ID}/artifacts/raw/capi/BUILD/altv-capi-client-linux.zip?inline=false\\\" },
        # { \\\"name\\\": \\\"client-linux\\\", \\\"url\\\": \\\"https://gitlab.com/7Hazard/altv-capi/-/jobs/${CI_JOB_ID}/artifacts/raw/capi/BUILD/altv-capi-client-static-linux.zip?inline=false\\\" },
        - "curl --header \"Content-Type: application/json\" --header \"PRIVATE-TOKEN: ${CI_GITLAB_API_PRIVATE_KEY}\" 
        --data \"{ \\\"name\\\": \\\"${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_IID}\\\", \\\"tag_name\\\": \\\"${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_IID}\\\", \\\"ref\\\": \\\"${CI_COMMIT_REF_SLUG}\\\", \\\"description\\\": \\\"Build ${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_IID}\\\", \\\"assets\\\": { \\\"links\\\": [
            { \\\"name\\\": \\\"server-win32\\\", \\\"url\\\": \\\"https://gitlab.com/7Hazard/altv-capi/-/jobs/${CI_JOB_ID}/artifacts/raw/build/altv-jvm-module-win32.zip?inline=false\\\" },
            { \\\"name\\\": \\\"server-linux\\\", \\\"url\\\": \\\"https://gitlab.com/7Hazard/altv-capi/-/jobs/${CI_JOB_ID}/artifacts/raw/build/altv-jvm-module-linux.zip?inline=false\\\" },
        ]} }\"
        --request POST https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/releases"
    
    artifacts:
        name: "altv-capi-${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_IID}"
        paths:
            - build/altv-jvm-module-win32.zip
            - build/altv-jvm-module-linux.zip
    
    only:
        refs:
            - master
